// void decimal_to_snafu(long n, char *output);
// void decimal_to_snafu_map(int n, char *output);
long snafu_to_int(char *s);
void decimal_to_snafu(long long n, char *output);
void decimal_to_snafu_map(int n, char *output);
bool is_lower_bound_available(int max_power, long input);
int max_power(long long input);
void run_lowerbound(long long input, int power, char *output);
int round_to_closest_int(float n);
void exit_if_over_two(float times);
